name: scheme_package
description: Scheme Library - Tools and Widgets to make development faster.
version: 0.0.2
homepage: https://github.com/Ammonious/scheme-package

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  division:
  firebase_storage:
  flutter_custom_clippers:
  google_fonts:
  boxicons_flutter:
  flutter_icons:
  flutter_svg:
  get_it:
  injectable:
  flutter_staggered_animations:
  cached_network_image:
  rxdart:
  flutter_hooks:
  build:
  source_gen:
  analyzer:
  draggable_scrollbar:
  path_provider:
  streaming_shared_preferences:
  flutter_cache_manager:
  flutter_inner_drawer:
  image:
  responsive_builder:
  image_picker:
  sa_stateless_animation:
  sa_multi_tween:
  sa_anicoto:
  video_player:
  share_extend:
  keyboard_visibility:
  flutter_screenutil:
  tinycolor:
  flutter_color:
  animations:
  flare_flutter:
  extended_image:
    git:
      url: git://github.com/jonataslaw/extended_image.git
  provider:
  clay_containers:
  flutter_neumorphic:
  auto_route:
  flutter_statusbarcolor:
  get:
  scheme_theme:
    git:
      url: "https://github.com/Ammonious/Scheme-Development.git"
      path: "lib/packages/scheme_theme/"


dev_dependencies:
  injectable_generator:
  auto_route_generator:
  build_runner:


flutter:
  assets:
    - assets/unicons/
    - assets/md_color/
    - assets/unicon_icons.flr
    - icons/round/
    - icons/twotone/

  fonts:
    - family: Bang
      fonts:
        - asset: fonts/bang.ttf
    - family: BoxIcons
      fonts:
          - asset: fonts/boxicons.ttf
